[package]
name = "bevy_fbx"
version = "0.1.0-dev"
edition = "2021"
repository = "https://github.com/HeavyRain266/bevy_fbx"
exclude = ["assets/**/*", "scripts/**/*", ".github/**/*"]
description = "Autodesl Filmbox (*.fbx) scene loader for Bevy Engine"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "bevy_plugin", "fbx_loader"]

[features]
profile = []
maya_3dsmax_pbr = []

[dependencies]
rgb = "0.8.33"
anyhow = "1.0.58"
glam = { version = "0.21", features = ["mint"] }
# fbxcel-dom = { version = "0.0.9", path = "../fbxcel-dom" }
fbxcel-dom = "0.0.9"

[dependencies.bevy]
version = "0.8.0"
default-features = false
features = [
  "tga",
  "bevy_pbr",
  "bevy_render",
  "bevy_winit",
  "bevy_scene",
  # "bevy_core_pipeline"
]

[[example]]
name = "cube"
path = "examples/cube.rs"

[[example]]
name = "scene_viewer"
path = "examples/scene_viewer.rs"

# [dev-dependencies]
# bevy-inspector-egui = "0.11"

[dev-dependencies.bevy]
version = "0.8.0"
default-features = false
features = [
  "x11", #"wayland",

  "tga", "dds",
  "bevy_pbr",
  "bevy_render",
  "bevy_winit",
  "bevy_scene",
  "filesystem_watcher",
  "bevy_core_pipeline"
]
